### ISSUE TITLE
Update for Gitlab API v4

### ISSUE THREAD

**Issue by zstumgoren** [associatedpress/datakit-gitlab#1]
The datakit-gitlab module breaks on the new(er) versions of Gitlab using the v4 API. We applied a small [hotfix](https://github.com/associatedpress/datakit-gitlab/commit/42a58d9a0efaf24b0a56a8180d429221db7b49d9), but more thorough testing for additional breakage should be performed.

Also, it would be nice to keep official support for Gitlab API v3 for anyone still on older versions of Gitlab. One possible way to handle may be to cut two releases to PyPI: 

* v0.1 supporting Gitlab API v3 (basically the current state of the code)
* v0.2. supporting Gitlab API v4 (the hotfix plus any other changes/tests necessary to port forward).

Should also tag and/or branch the original code on Github so that anyone still on v3 can fork and develop more easily if the need arises.

**Comment by myersjustinc** [comment]
I don't feel particularly compelled to maintain v3 support within the main codebase. [v4's been the preferred version](https://docs.gitlab.com/ee/api/v3_to_v4.html) since GitLab 9.0 ([two and a half years ago](https://gitlab.com/gitlab-org/gitlab-foss/blob/v9.0.1/CHANGELOG.md)), and v3's been removed altogether since GitLab 11.0 [more than a year ago](https://gitlab.com/gitlab-org/gitlab-foss/blob/v11.0.0/CHANGELOG.md).

[I added a commit to the `hotfix` branch](https://github.com/associatedpress/datakit-gitlab/commit/050d242ae5fb89a1b313292a6b170049ed42b681) to ensure the `python-gitlab` dependency gets upgraded when `datakit-gitlab` does.

I'm fine with your two-release strategy if we really feel like we need a solution for GitLab 8.x and older. I wouldn't use v0.1 and v0.2, though, since [we're already at v0.2 due to the colons-to-spaces transition](https://github.com/associatedpress/datakit-gitlab/commit/26cb8a443b6d9f506223cbe15edc9c61dba84590). Maybe v0.2 and v0.3?

**Comment by myersjustinc** [comment]
We just pushed v0.2.0 and v0.3.0 to PyPI; v0.2.0 provides API v3 support, and v0.3.0+ provide API v4 support. Tests will need some work, but that's for another ticket (and probably another day).
